export const SET_SORT_ORDER = 'SET_SORT_ORDER'

export const SET_FILTER = 'SET_FILTER'
export const SET_ALL_FILTERS = 'SET_ALL_FILTERS'

export const FETCH_TICKETS_REQUEST = 'FETCH_TICKETS_REQUEST'
export const FETCH_TICKETS_SUCCESS = 'FETCH_TICKETS_SUCCESS'
export const FETCH_TICKETS_FAILURE = 'FETCH_TICKETS_FAILURE'
